[project]
name = "self-learn-face-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "insightface>=0.7.3",
    "onnxruntime>=1.23.2",
    "onnxruntime-gpu>=1.23.2",
    "opencv-python>=4.12.0.88",
]
